### PR TITLE
Ignore fsd_slice_import_rule in app/ layer

### LINKED ISSUE #2: fsd_slice_import rule triggered by segments importing from each other in app/ layer
## Description

Currently, the fsd_slice_import rule is triggered in the following situation:

`lib/src/app/routes/router.dart` imports `lib/src/app/layout/layout.dart`.

However, the [FSD documentation](https://feature-sliced.design/docs/reference/layers#import-rule-on-layers) states that segments in the app layer should be able to imports each other freely since they are segments.

> Layers App and Shared are exceptions to this rule — they are both a layer and a slice at the same time. Slices partition code by business domain, and these two layers are exceptions because Shared does not have business domains, and App combines all business domains.
> 
> In practice, this means that layers App and Shared are made up of segments, and segments can import each other freely.

## Possible solution

If I am not mistaken I think we would only need to add this check in the following `_checkImport` method inside `lib/src/lints/fsd_slice_import_lint.dart` to also make an exception for the app layer.

```dart
  void _checkImport(
    ImportDirective node,
    CustomLintResolver resolver,
    DiagnosticReporter reporter,
  ) {
    final importUri = node.uri.stringValue;
    if (importUri == null) return;

    // 현재 파일의 Slice
    final currentSlice = FsdSlice.fromPath(resolver.path);
    if (currentSlice == null) return;

    // app and shared 레이어는 검사하지 않음
    if (currentSlice.layer == FsdLayer.app || currentSlice.layer == FsdLayer.shared) return;

   [...]
```

@dennis-emstone

### PR DESCRIPTION
**Pull request by WilliamHarvey97**
fixes #2 

With the updated example, I had before changes:

```
$ dart run custom_lint
Building package executable... 
Built custom_lint:custom_lint.
Analyzing...                           0.0s

  lib/app/routes/router.dart:1:1 • Slice "FsdLayer.app/routes" cannot directly import from slice "FsdLayer.app/layout" in the same layer. • fsd_slice_import • ERROR
  lib/entities/user/bad_layer_import.dart:2:1 • Layer "entities" cannot import from layer "features". Only lower layers can be imported. Layer hierarchy: app > pages > widgets > features > entities > shared • fsd_layer_import • ERROR
  lib/entities/user/bad_relative_layer_import.dart:2:1 • Layer "entities" cannot import from layer "features". Only lower layers can be imported. Layer hierarchy: app > pages > widgets > features > entities > shared • fsd_layer_import • ERROR
  lib/entities/user/bad_slice_import_from_file.dart:1:1 • Slice "FsdLayer.entities/user" cannot directly import from slice "FsdLayer.entities/invoice" in the same layer. • fsd_slice_import • ERROR
  lib/features/login/bad_relative_slice_import.dart:2:1 • Slice "FsdLayer.features/login" cannot directly import from slice "FsdLayer.features/payment" in the same layer. • fsd_slice_import • ERROR
  lib/features/login/bad_slice_import.dart:2:1 • Slice "FsdLayer.features/login" cannot directly import from slice "FsdLayer.features/payment" in the same layer. • fsd_slice_import • ERROR

6 issues found.
```

After changes:

```
$ dart run custom_lint
Analyzing...                           0.0s

  lib/entities/user/bad_layer_import.dart:2:1 • Layer "entities" cannot import from layer "features". Only lower layers can be imported. Layer hierarchy: app > pages > widgets > features > entities > shared • fsd_layer_import • ERROR
  lib/entities/user/bad_relative_layer_import.dart:2:1 • Layer "entities" cannot import from layer "features". Only lower layers can be imported. Layer hierarchy: app > pages > widgets > features > entities > shared • fsd_layer_import • ERROR
  lib/entities/user/bad_slice_import_from_file.dart:1:1 • Slice "FsdLayer.entities/user" cannot directly import from slice "FsdLayer.entities/invoice" in the same layer. • fsd_slice_import • ERROR
  lib/features/login/bad_relative_slice_import.dart:2:1 • Slice "FsdLayer.features/login" cannot directly import from slice "FsdLayer.features/payment" in the same layer. • fsd_slice_import • ERROR
  lib/features/login/bad_slice_import.dart:2:1 • Slice "FsdLayer.features/login" cannot directly import from slice "FsdLayer.features/payment" in the same layer. • fsd_slice_import • ERROR

5 issues found.
```

### CODE REVIEW

File: example/lib/entities/user/bad_relative_layer_import.dart [hunk 1]
```diff
@@ -2,5 +2,7 @@
 import '../../features/login/login_flow.dart';
 
 class BadRelativeLayerImport {
-  // This class doesn't need to do anything, it just needs the import.
+  final LoginFlow loginFlow;
+
+  BadRelativeLayerImport(this.loginFlow);
```
Comment (WilliamHarvey97) [inline example/lib/entities/user/bad_relative_layer_import.dart:7]: added this just to remove the unused_import dart linting error

Image

File: example/lib/features/login/bad_relative_slice_import.dart [hunk 2]
```diff
@@ -2,5 +2,7 @@
 import '../payment/payment.dart';
 
 class BadRelativeSliceImport {
-  // This class doesn't need to do anything, it just needs the import.
+  final Payment payment;
+
+  BadRelativeSliceImport(this.payment);
```
Comment (WilliamHarvey97) [inline example/lib/features/login/bad_relative_slice_import.dart:7]: same

**Comment by dennis-emstone** [comment]
Thanks your contribution.

**Review by dennis-emstone — APPROVED** [review]

**Comment by JeMigli** [comment]
@WilliamHarvey97 @dennis-emstone  Keep up the good work 👍
